---

# The Ansible initial user it's the user created in local tests, get for the ansible facts.

- name: "Create .ssh directory for initial user"
  file:
    path: "{{ ansible_user_dir }}/.ssh"
    owner: "{{ ansible_user_id }}"
    state: "directory"
    mode: "0700"

- name: "Add keys to the initial user"
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.ssh"
    owner: "{{ ansible_user_id }}"
    mode: "0600"
  with_items:
      - "id_rsa"
      - "id_rsa.pub"

- name: "Add authorized keys for the initial user to can connect through SSH to the same user"
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ lookup('file', '{{ ansible_user_dir }}/.ssh/id_rsa.pub') }}"
    state: "present"
