---

- name: "Add and enable repository for Nginx"
  yum_repository:
    name: "nginx"
    description: "nginx repo"
    baseurl: "http://nginx.org/packages/centos/7/$basearch/"
    gpgcheck: "no"
    enabled: "yes"

- name: "Install Nginx"
  package:
    name: "nginx"
    state: "present"
